import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeAdditional,planAdditional} from '../lib/additional-sources';
const now=new Date('2026-10-09T12:00:00Z');
const h={title:'Engineer',companyName:'Test',description:'Build software remotely.',locationRestrictions:[],timezoneRestrictions:[8],employmentType:'Full Time',pubDate:1791504000,expiryDate:1792108800,applicationLink:'https://himalayas.app/companies/test/jobs/engineer',parentCategories:['Software Engineering'],minSalary:1000,maxSalary:2000,currency:'USD',salaryPeriod:'monthly'};
test('Recruiting pools and source test listings stay out; explicit title restrictions require review',()=>{for(const title of ['Open Application','Prospective Employees','Sales Expression of Interest Form','QA Tester (Future Roles)','Bewerberpool','Work With Us!','Test job - This is for testing purposes only'])assert.equal(normalizeAdditional('himalayas',{...h,title},now),null);assert.equal(normalizeAdditional('himalayas',{...h,title:'Security Analyst (Europe or LATAM, Remote)'},now)?.status,'pending');assert.equal(normalizeAdditional('himalayas',{...h,title:'QA Test Engineer'},now)?.status,'approved');});
test('Himalayas validates country, timezone, expiry, timestamps and attribution',()=>{const j=normalizeAdditional('himalayas',h,now)!;assert.equal(j.status,'approved');assert.equal(j.importInfo?.source,'Himalayas');assert.match(j.salary,/monthly/);assert.equal(normalizeAdditional('himalayas',{...h,locationRestrictions:[{alpha2:'US'}]},now),null);assert.equal(normalizeAdditional('himalayas',{...h,timezoneRestrictions:[-5]},now),null);assert.equal(normalizeAdditional('himalayas',{...h,expiryDate:1},now),null);assert.equal(normalizeAdditional('himalayas',{...h,timezoneRestrictions:undefined},now),null);});
test('Additional source contradictions remain hidden and unknown employment is excluded',()=>{assert.equal(normalizeAdditional('himalayas',{...h,description:'Candidates must reside in Canada.'},now)?.status,'pending');assert.equal(normalizeAdditional('himalayas',{...h,employmentType:'Other'},now),null);assert.equal(normalizeAdditional('himalayas',{...h,applicationLink:'https://evil.example/jobs'},now),null);});
test('Repeated and cross-source jobs deduplicate; partial page imports never deactivate unseen records',()=>{const j=normalizeAdditional('himalayas',h,now)!;assert.equal(planAdditional('himalayas',[h,h],[j],now).summary.published,0);assert.equal(planAdditional('himalayas',[],[j],now).changes.length,0);assert.equal(planAdditional('himalayas',[h],[{...j,id:'another-source'}],now).summary.duplicates,1);});
test('Jobicy preserves original application links and does not invent salary or expiry',()=>{const j=normalizeAdditional('jobicy',{jobTitle:'Engineer',companyName:'Test',jobDescription:'Remote work worldwide.',jobGeo:'Anywhere',jobType:['Contract'],pubDate:'2026-10-09T01:00:00Z',url:'https://jobicy.com/jobs/1-engineer'},now)!;assert.equal(j.status,'approved');assert.equal(j.applicationUrl,'https://jobicy.com/jobs/1-engineer');assert.match(j.salary,/Not disclosed/);assert.ok(j.importInfo?.expiresAt);});
test('Remote OK missing location and missing employment never become fabricated listings',()=>{const r={position:'Engineer',company:'Test',description:'Full-time remote engineer.',date:'2026-10-09T01:00:00Z',url:'https://remoteok.com/remote-jobs/1'};assert.equal(normalizeAdditional('remoteok',r,now),null);assert.equal(normalizeAdditional('remoteok',{...r,location:'Worldwide',description:'Engineer'},now),null);});

test('Support imports keep region conflicts and non-job pools out of publication',()=>{for(const title of ['Spontaneous Application','Request for Proposal - Travel Company',"Apply to NISC Teams"])assert.equal(normalizeAdditional('himalayas',{...h,title},now),null);for(const description of ['Location: LATAM, 100% Remote.','Location: Latin American countries within the EST zone.','Location: Remote - Plymouth, MN','You are located in EMEA.'])assert.equal(normalizeAdditional('himalayas',{...h,description},now)?.status,'pending');assert.equal(normalizeAdditional('himalayas',{...h,title:'Customer Experience Agent (Europe)'},now)?.status,'pending');});
