import {test} from 'node:test';
import assert from 'node:assert/strict';
import {minorAmount,checkoutUrl,matchesPayment} from '../lib/wire-policy';
import {ownerPaymentTest} from '../lib/wire-owner-test';
test('Owner test is restricted to an exact account and expiry',()=>{const until='2026-10-11T14:40:00Z',now=Date.parse('2026-10-10T14:40:00Z');assert.equal(ownerPaymentTest('owner@example.com','owner@example.com',until,now),true);for(const email of [null,'other@example.com','owner@example.com.evil'])assert.equal(ownerPaymentTest(email,'owner@example.com',until,now),false);assert.equal(ownerPaymentTest('owner@example.com','owner@example.com',until,Date.parse(until)),false);assert.equal(ownerPaymentTest('owner@example.com',undefined,undefined,now),false);});
test('500 MNT test must match the exact provider amount',()=>{assert.equal(minorAmount(500),500);assert.throws(()=>minorAmount(499));const order={id:'owner-test',wire_intent:'pi_test',amount:500};const pi={id:'pi_test',amount:500,currency:'MNT',status:'succeeded',livemode:true,metadata:{order_id:'owner-test'}};assert.equal(matchesPayment(pi,order,true),true);assert.equal(matchesPayment({...pi,amount:50000},order,true),false);});
test('Non-test pricing conversion remains unchanged',()=>{assert.equal(minorAmount(10000),1000000);assert.throws(()=>minorAmount(1.5));});
test('checkout redirects accept only hosted Wire checkout',()=>{assert.equal(checkoutUrl('https://pay.wire.mn/c/token'),'https://pay.wire.mn/c/token');for(const url of ['https://evil.test/c/token','http://pay.wire.mn/c/token','https://pay.wire.mn.evil.test/c/x','https://user:pw@pay.wire.mn/c/x'])assert.throws(()=>checkoutUrl(url));});
test('payment must match amount, currency, order, intent and mode',()=>{const order={id:'order',wire_intent:'pi_1',amount:10000},pi={id:'pi_1',amount:1000000,currency:'MNT',status:'succeeded',livemode:true,metadata:{order_id:'order'}};assert.equal(matchesPayment(pi,order,true),true);for(const change of [{amount:10000},{currency:'USD'},{livemode:false},{id:'pi_2'},{metadata:{order_id:'other'}}])assert.equal(matchesPayment({...pi,...change},order,true),false);});

import {createHmac} from 'node:crypto';
import {verifyWireSignature} from '../lib/wire-signature';
test('Webhook rejects tampering, expired signatures and missing secrets',()=>{const raw=Buffer.from('{\"type\":\"payment_intent.succeeded\"}'),secret='test-secret',now=1700000000000,t=String(now/1000);const sig=createHmac('sha256',secret).update(t+'.').update(raw).digest('hex'),header='t='+t+',v1='+sig;assert.equal(verifyWireSignature(raw,header,secret,now),true);assert.equal(verifyWireSignature(Buffer.from('tampered'),header,secret,now),false);assert.equal(verifyWireSignature(raw,header,secret,now+301000),false);assert.equal(verifyWireSignature(raw,header,'',now),false);});
