'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import type {Lang} from '@/lib/i18n';
import {safeNext} from '@/lib/member-policy';
export default function Account({lang,email,name,signupOpen,reset,next,authError}:{lang:Lang;email?:string;name?:string;signupOpen:boolean;reset:boolean;next?:string;authError:boolean}){
 const mn=lang==='mn',router=useRouter(),[mode,setMode]=useState<'login'|'signup'|'forgot'>('login'),[busy,setBusy]=useState(false),[message,setMessage]=useState(authError?(mn?'Баталгаажуулах холбоос хүчингүй эсвэл хугацаа дууссан. Дахин оролдоно уу.':'The confirmation link is invalid or expired. Try again.'):'');
 async function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();setBusy(true);setMessage('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{const response=await fetch('/api/member/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,action,acceptTerms:fields.acceptTerms==='on'})});if(!response.ok)throw new Error();if(action==='login'){router.push(safeNext(next??null)+((safeNext(next??null)==='/account')?'?lang='+lang:''));router.refresh();}else if(action==='logout'){router.refresh();}else if(action==='signup'||action==='forgot'){setMessage(mn?'Имэйлээ шалгаж баталгаажуулах холбоосыг нээнэ үү. Ирэхгүй бол түр хүлээгээд дахин оролдоорой.':'Check your inbox for a confirmation link. If it does not arrive, wait before retrying.');}else{setMessage(mn?'Амжилттай хадгаллаа.':'Saved successfully.');router.refresh();}}catch{setMessage(mn?'Амжилтгүй боллоо. Мэдээлэл, имэйл баталгаажуулалтаа шалгаад дахин оролдоно уу.':'Unable to complete this action. Check your details and email confirmation, then retry.');}finally{setBusy(false);}}
 return <section className="panel account-card"><p role="status" className="notice">{message}</p>{email?<><p>{email}</p><form onSubmit={e=>submit(e,'profile')} className="job-form"><label>{mn?'Таны нэр':'Your name'}<input name="name" required maxLength={80} defaultValue={name}/></label><button disabled={busy} className="button small">{mn?'Нэр хадгалах':'Save name'}</button></form><details open={reset}><summary>{mn?'Нууц үг шинэчлэх':'Update password'}</summary><form className="job-form" onSubmit={e=>submit(e,'password')}><label>{mn?'Шинэ нууц үг (хамгийн багадаа 8 тэмдэгт)':'New password (at least 8 characters)'}<input required type="password" name="password" minLength={8} maxLength={128} autoComplete="new-password"/></label><button disabled={busy} className="button small">{mn?'Нууц үг хадгалах':'Save password'}</button></form></details><form onSubmit={e=>submit(e,'logout')}><button disabled={busy} className="text-button">{mn?'Гарах':'Sign out'}</button></form></>:<><div className="account-tabs">{(['login','signup','forgot'] as const).map((action,i)=><button type="button" className={mode===action?'button small':'text-button'} key={action} onClick={()=>{setMode(action);setMessage('');}}>{(mn?['Нэвтрэх','Бүртгүүлэх','Нууц үг мартсан']:['Sign in','Register','Forgot password'])[i]}</button>)}</div>{mode!=='login'&&!signupOpen?<p className="notice">{mn?'Имэйл илгээх үйлчилгээ тохируулсны дараа бүртгэл болон нууц үг сэргээх нээгдэнэ.':'Registration and password recovery will open after email delivery is configured.'}</p>:<form className="job-form" onSubmit={e=>submit(e,mode)}><label>{mn?'Имэйл':'Email'}<input required type="email" name="email" maxLength={254} autoComplete="email"/></label>{mode!=='forgot'&&<label>{mn?'Нууц үг (хамгийн багадаа 8 тэмдэгт)':'Password (at least 8 characters)'}<input required type="password" name="password" minLength={8} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/></label>}{mode==='signup'&&<label className="checkbox"><input required type="checkbox" name="acceptTerms"/><span><Link href={`/terms?lang=${lang}`}>{mn?'Үйлчилгээний нөхцөл':'Terms'}</Link> {mn?'болон':'and'} <Link href={`/privacy?lang=${lang}`}>{mn?'нууцлалын мэдээллийг уншиж зөвшөөрч байна.':'Privacy notice accepted.'}</Link></span></label>}<button className="button" disabled={busy}>{busy?(mn?'Түр хүлээнэ үү…':'Please wait…'):(mn?{login:'Нэвтрэх',signup:'Бүртгүүлэх',forgot:'Сэргээх холбоос авах'}:{login:'Sign in',signup:'Register',forgot:'Send reset link'})[mode]}</button></form>}</>}</section>;
}
