'use client';
import {useState} from 'react';
import {createApplicationDocuments,type ApplicationDetails} from '@/lib/application-documents';
const empty:ApplicationDetails={name:'',email:'',location:'',role:'',company:'',summary:'',skills:'',experience:'',education:'',languages:'',availability:'',motivation:''};
export default function ApplicationBuilder({mn}:{mn:boolean}){
 const [details,setDetails]=useState(empty),[cv,setCv]=useState(''),[letter,setLetter]=useState(''),[message,setMessage]=useState('');
 const fields:[keyof ApplicationDetails,string,string][]=[['name','Нэр','Full name'],['email','Имэйл','Email'],['location','Хот, улс','City, country'],['role','Албан тушаал','Role title'],['company','Компани (cover letter-д)','Company (for cover letter)'],['summary','Өөрийн тухай товч — англиар','Profile — in English'],['skills','Ур чадвар — англиар','Skills — in English'],['experience','Бодит туршлага / төсөл — англиар','Real experience / projects — in English'],['education','Боловсрол / сургалт — англиар','Education / training — in English'],['languages','Хэл, бодит түвшин — англиар','Languages and honest proficiency — in English'],['availability','Ажиллах цаг, цагийн бүс — англиар','Availability and time zone — in English'],['motivation','Энэ ажилд тохирох шалтгаан — англиар','Why this role fits — in English']];
 function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function print(text:string,title:string){const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:0;height:0;border:0';document.body.appendChild(frame);const doc=frame.contentDocument;if(!doc||!frame.contentWindow){frame.remove();return;}doc.title=title;const style=doc.createElement('style');style.textContent='@page{size:A4;margin:20mm}body{font-family:Arial,sans-serif;color:#13243a}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12pt/1.55 Arial,sans-serif}';doc.head.appendChild(style);const content=doc.createElement('pre');content.textContent=text;doc.body.appendChild(content);frame.contentWindow.focus();frame.contentWindow.print();setTimeout(()=>frame.remove(),60000);}
 return <section className="panel"><h2>{mn?'CV, cover letter бэлдэх':'Build your CV and cover letter'}</h2><p>{mn?'Өөрийн үнэн мэдээллийг англиар бөглөөрэй. Энэ хэрэгсэл таны бичсэнийг загварт оруулна; орчуулга, AI үнэлгээ хийхгүй. Мэдээлэл серверт хадгалагдахгүй; хуудас хаахад арилна.':'Enter your real information in English. This tool formats what you write; it does not translate or assess your qualifications. Your entries are not stored on our server and disappear when you leave.'}</p><form onSubmit={e=>{e.preventDefault();const output=createApplicationDocuments(details);setCv(output.cv);setLetter(output.letter);setMessage(mn?'Доорх эхийг шалгаж, зассаны дараа татна уу.':'Review and edit the drafts below before downloading.');}}><div className="benefit-grid">{fields.map(([key,mongolian,english],i)=><label key={key} style={{display:'grid',gap:8,minWidth:0}}><span>{mn?mongolian:english}</span>{i<5?<input required={key==='name'||key==='email'||key==='role'} type={key==='email'?'email':'text'} maxLength={200} value={details[key]} onChange={e=>setDetails({...details,[key]:e.target.value})}/>:<textarea rows={3} maxLength={5000} value={details[key]} onChange={e=>setDetails({...details,[key]:e.target.value})}/>}</label>)}</div><button className="button" type="submit" style={{marginTop:20}}>{mn?'Загвар бэлдэх':'Generate drafts'}</button></form><p role="status">{message}</p>{cv&&<><p>{mn?'PDF хадгалах: хэвлэх цонхны Destination хэсэгт Save as PDF сонгоно. Төхөөрөмжөөс хамаарч нэр нь өөр байж болно.':'To save a PDF, select Save as PDF in the print dialog. The option may vary by device.'}</p>{[['CV',cv,setCv],['Cover letter',letter,setLetter]].map(([title,value,setter])=><div key={title as string} style={{marginTop:24}}><h3>{title as string}</h3><textarea aria-label={title as string} rows={16} style={{width:'100%'}} value={value as string} onChange={e=>(setter as typeof setCv)(e.target.value)}/><div style={{display:'flex',flexWrap:'wrap',gap:12,marginTop:12}}><button className="button secondary" onClick={()=>download(value as string,title==='CV'?'ajilgo-cv.txt':'ajilgo-cover-letter.txt')}>{mn?'Текст татах':'Download text'}</button><button className="button" onClick={()=>print(value as string,title as string)}>{mn?'PDF хадгалах / хэвлэх':'Save PDF / print'}</button></div></div>)}</>}</section>;
}
