import 'server-only';
import {HttpError} from './http';
import {checkoutUrl,minorAmount,type WireIntent} from './wire-policy';
export const wireConfigured=()=>!!process.env.WIRE_API_KEY&&['test','live'].includes(process.env.WIRE_MODE||'')&&(process.env.WIRE_MODE==='test'?process.env.WIRE_API_KEY.startsWith('sk_test_'):process.env.WIRE_API_KEY.startsWith('sk_live_'));
export const wireOpen=()=>wireConfigured()&&process.env.WIRE_PAYMENTS_ENABLED==='true';
export async function wireRequest(path:string,data?:Record<string,unknown>,key?:string){if(!wireConfigured())throw new HttpError(503,'Wire is not configured');const response=await fetch('https://api.wire.mn/v1/'+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+process.env.WIRE_API_KEY,'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:data?JSON.stringify(data):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new HttpError(503,'Payment provider unavailable');return response.json();}
export async function retrieveIntent(id:string):Promise<WireIntent>{if(!/^pi_[a-zA-Z0-9_-]+$/.test(id))throw new HttpError(400,'Invalid payment');return wireRequest('payment_intents/'+encodeURIComponent(id));}
export async function createCheckout(order:{id:string;amount:number;wire_intent:string|null},lang:string){let intent=order.wire_intent;if(!intent){const pi=await wireRequest('payment_intents',{amount:minorAmount(order.amount),currency:'MNT',description:'Remote Job Mongolia membership',allowed_operators:process.env.WIRE_MODE==='test'?['sandbox']:(process.env.WIRE_OPERATORS||'').split(',').filter(Boolean),metadata:{order_id:order.id}},'rjm-intent-'+order.id);if(typeof pi.id!=='string'||!/^pi_[a-zA-Z0-9_-]+$/.test(pi.id))throw new HttpError(503,'Invalid provider response');intent=pi.id;}
const site=new URL(process.env.SITE_URL!);if(site.protocol!=='https:')throw new HttpError(503,'HTTPS site required');const session=await wireRequest('checkout/sessions',{payment_intent:intent,success_url:site.origin+'/membership?lang='+lang,cancel_url:site.origin+'/membership?lang='+lang},'rjm-checkout-'+order.id);return {intent,url:checkoutUrl(session.url)};}
