// Targeted Himalayas search; retains attribution, eligibility checks and free application links.
import {createHash} from 'node:crypto';
import {promises as fs} from 'node:fs';
import {planAdditional,normalizeAdditional} from '../lib/additional-sources';
import {roleCategory} from '../lib/job-discovery';
if(process.env.SUPABASE_URL===undefined)process.loadEnvFile('.env.local');
async function main(){const {getJobs,saveJobs}=await import('../lib/store');const terms=['customer support','customer service','virtual assistant','administrative assistant','content moderator','support agent','customer success','technical support','chat support','email support','help desk','call center','support representative'];const raw:Record<string,unknown>[]=[],seen=new Set<string>();let pages=0,cachedPages=0;await fs.mkdir('.data',{recursive:true});for(const q of terms){for(let page=1;page<=10;page++){const url=new URL('https://himalayas.app/jobs/api/search');url.searchParams.set('q',q);url.searchParams.set('country','MN');url.searchParams.set('sort','recent');url.searchParams.set('page',String(page));const file='.data/support-search-'+createHash('sha256').update(url.href).digest('hex').slice(0,20)+'.json';let feed;try{const stat=await fs.stat(file);if(Date.now()-stat.mtimeMs<86400000){feed=JSON.parse(await fs.readFile(file,'utf8'));cachedPages++;}}catch{}if(!feed){const r=await fetch(url,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Search HTTP '+r.status);feed=await r.json();if(!Array.isArray(feed.jobs))throw new Error('Malformed feed');await fs.writeFile(file,JSON.stringify(feed));}pages++;let added=0;for(const item of feed.jobs){const id=String(item.guid||item.id);if(!seen.has(id)){seen.add(id);raw.push(item);added++;}}if(!feed.jobs.length||!added||page*feed.jobs.length>=Number(feed.totalCount))break;}}
const existing=await getJobs(),plan=planAdditional('himalayas',raw,existing);const withdrawn=raw.filter(item=>!normalizeAdditional('himalayas',item)).map(item=>{const url=String(item.applicationLink||item.guid||'');return existing.find(j=>j.importInfo?.source==='Himalayas'&&j.applicationUrl===url);}).filter(Boolean);const changes=plan.changes.map(j=>({...j,category:roleCategory(j.title,j.category),membersOnly:false}));for(const j of withdrawn){if(j&&!changes.some(c=>c.id===j.id))changes.push({...j,status:'pending',membersOnly:false,importInfo:{...j.importInfo!,active:false,reason:'No longer passes listing and eligibility screening.'}});}for(const j of existing){if(!j.importInfo||changes.some(c=>c.id===j.id))continue;const category=roleCategory(j.title,j.category);if(category!==j.category||j.membersOnly)changes.push({...j,category,membersOnly:false});}await saveJobs(changes);await fs.writeFile('.data/support-import-summary.json',JSON.stringify({...plan.summary,pages,cachedPages,checkedAt:new Date().toISOString()},null,2));console.log({...plan.summary,pages,cachedPages,updated:changes.length});}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
