// Isolated fake HTTP transport: never sends a request, email or money to Wire.
import assert from 'node:assert/strict';
import {createCheckout,retrieveIntent} from '../lib/wire';
process.env.WIRE_API_KEY='sk_test_disposable_mock';process.env.WIRE_MODE='test';process.env.SITE_URL='https://remote-job-mongolia-1gys.vercel.app';
const original=globalThis.fetch,calls:{url:string;options:RequestInit}[]=[];
globalThis.fetch=(async(url,options)=>{calls.push({url:String(url),options:options||{}});return Response.json(String(url).endsWith('/checkout/sessions')?{url:'https://pay.wire.mn/c/test'}:{id:'pi_test',amount:10000,currency:'MNT',status:'requires_payment_method',livemode:false});}) as typeof fetch;
async function main(){try{const order={id:'stable-order-id',amount:10000,wire_intent:null};const first=await createCheckout(order,'mn'),second=await createCheckout(order,'mn');assert.deepEqual(first,second);assert.equal(calls.length,4);for(const i of [0,2]){const params=JSON.parse(String(calls[i].options.body));assert.equal(params.amount,10000);assert.deepEqual(params.allowed_operators,['sandbox']);assert.equal(params.metadata.order_id,order.id);assert.equal(new Headers(calls[i].options.headers).get('Idempotency-Key'),'rjm-intent-'+order.id);}assert.equal(JSON.parse(String(calls[1].options.body)).payment_intent,'pi_test');assert.equal(new Headers(calls[1].options.headers).get('Idempotency-Key'),'rjm-checkout-'+order.id);await assert.rejects(()=>retrieveIntent('../escape'));globalThis.fetch=(async()=>new Response('{}',{status:401})) as typeof fetch;await assert.rejects(()=>retrieveIntent('pi_test'));globalThis.fetch=(async(url)=>Response.json(String(url).endsWith('/checkout/sessions')?{url:'https://evil.invalid/c/x'}:{id:'pi_test'})) as typeof fetch;await assert.rejects(()=>createCheckout(order,'mn'));console.log('PASS: amount units, sandbox-only creation, stable retry keys, hosted checkout binding, invalid IDs, provider failure and unsafe redirects. Mock transport only.');}finally{globalThis.fetch=original;}
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});

