import {notFound} from 'next/navigation';
import {memberOnly} from '@/lib/member-policy';
import Link from 'next/link';
import {getPublicJob} from '@/lib/public-job-store';
import {publicJobs} from '@/lib/jobs';
import ImportInfo from '@/components/import-info';
import {seo,pageUrl} from '@/lib/seo';
import {mongolianTranslationUrl} from '@/lib/translation';
import {copy,language,option} from '@/lib/i18n';
export async function generateMetadata({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{lang?:string}>}){const {id}=await params,lang=language((await searchParams).lang),job=await getPublicJob(id);return job?seo(`/jobs/${id}`,lang,`${job.title} · ${job.company}`,`${option(job.remoteType,lang)} · ${job.salary}. ${job.description.slice(0,130)}`):{title:'Job not found',robots:{index:false}};}
export default async function Detail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{lang?:string}>}){const {id}=await params,lang=language((await searchParams).lang),t=copy[lang],job=await getPublicJob(id);if(!job)notFound();const sample=job.applicationUrl==='https://example.com';return <main lang={lang} className="shell detail-page"><Link className="back" href={`/?lang=${lang}`}>‹ {t.back}</Link><div className="detail-title"><div className="company-logo">{job.company[0]}</div><div><p>{job.company}</p><h1>{job.title}</h1><span>{option(job.remoteType,lang)} · {option(job.employment,lang)}</span></div></div><div className="detail-grid"><article className="panel"><h2>{t.about}</h2><div className="translation-tools"><a className="button small" href={mongolianTranslationUrl(pageUrl(`/jobs/${job.id}`,'en'))} target="_blank" rel="noopener noreferrer">{lang==='mn'?'Монголоор орчуулах ↗':'Read in Mongolian ↗'}</a><p className="muted">{lang==='mn'?'Google Translate шинэ табаар нээгдэнэ. Автомат орчуулга алдаатай байж болох тул чухал шаардлагыг эх зарын мэдээлэлтэй тулгаарай.':'Google Translate opens in a new tab. Automatic translation may contain errors; check important requirements against the original listing.'}</p></div>{job.importInfo&&<ImportInfo job={job} lang={lang}/>}<div className="description">{job.description}</div></article><aside className="panel overview"><h2>{t.details}</h2>{(['salary','location','remoteType','category','employment'] as const).map(k=><div className="detail-item" key={k}><span>{k==='remoteType'?t.remote:t[k]}</span><strong>{option(job[k],lang)}</strong></div>)}<p className="member-badge">{memberOnly(job)?(lang==='mn'?'Membership шаардлагатай':'Membership required'):(lang==='mn'?'Үнэгүй apply':'Free application access')}</p>{memberOnly(job)&&<p>{lang==='mn'?'Идэвхтэй membership эрхтэй account-аар нэвтэрч apply холбоосыг нээнэ.':'Sign in with an active membership to open the application link.'}</p>}{sample?<p className="notice">{t.sample}</p>:<a className="button" href={`/apply/${job.id}?lang=${lang}`} target="_blank" rel="noopener noreferrer">{job.importInfo?(lang==='mn'?job.importInfo.source+' дээр үзэж, хүсэлт илгээх':'View and apply on '+job.importInfo.source):t.apply}</a>}</aside></div></main>}

