import {randomUUID} from 'node:crypto';
import {memberUser,memberDb,membershipPlan} from '@/lib/member';
import {body,sameOrigin,HttpError,errorResponse} from '@/lib/http';
import {consumeLimit} from '@/lib/security-store';
import {wireOpen,createCheckout,retrieveIntent} from '@/lib/wire';
import {matchesPayment} from '@/lib/wire-policy';
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({error:'Forbidden'},{status:403});try{const user=await memberUser();if(!user)throw new HttpError(401,'Sign in required');if(!wireOpen())throw new HttpError(503,'Wire payments are not open');if(!await consumeLimit('wire:'+user.id,20,60000))throw new HttpError(429,'Try later');const data=await body(request),db=memberDb();
if(data.action==='check'){const {data:order,error}=await db.from('membership_orders').select('id,amount,status,wire_intent').eq('id',String(data.orderId)).eq('user_id',user.id).eq('provider','wire').single();if(error||!order?.wire_intent)throw new HttpError(404,'Payment not found');const pi=await retrieveIntent(order.wire_intent);if(!matchesPayment(pi,order,process.env.WIRE_MODE==='live'))throw new HttpError(409,'Payment does not match');if(pi.status==='succeeded'){if(process.env.WIRE_MODE==='test')return Response.json({status:'test_succeeded'});const result=await db.rpc('rjm_settle_wire',{order_id:order.id,intent_id:pi.id});if(result.error)throw new HttpError(503,'Unable to activate membership');return Response.json({status:'approved'});}if(pi.status==='canceled')await db.from('membership_orders').update({status:'rejected',reviewed_at:new Date().toISOString(),reviewed_by:'wire-canceled'}).eq('id',order.id).eq('status','pending');return Response.json({status:pi.status});}
if(process.env.WIRE_MODE==='live'){if(process.env.MEMBER_SIGNUP_ENABLED!=='true')throw new HttpError(503,'Public signup is not ready');const {getJobs}=await import('@/lib/store');const {publicJobs}=await import('@/lib/jobs');const {memberOnly}=await import('@/lib/member-policy');if(!publicJobs(await getJobs()).some(memberOnly))throw new HttpError(503,'Membership listings are not ready');}if(data.action!=='checkout')throw new HttpError(400,'Invalid action');const plan=await membershipPlan();if(plan.refund_policy.trim().length<20||!process.env.SUPPORT_EMAIL)throw new HttpError(503,'Configure payment terms and support first');let {data:order,error}=await db.from('membership_orders').select('id,amount,wire_intent,checkout_url,provider,created_at').eq('user_id',user.id).eq('status','pending').maybeSingle();if(error)throw new HttpError(503,'Order lookup failed');if(!order){const id=randomUUID();const result=await db.from('membership_orders').insert({id,user_id:user.id,amount:plan.amount,duration_days:plan.duration_days,payment_reference:'WIRE_'+id,provider:'wire'}).select('id,amount,wire_intent,checkout_url,provider,created_at').single();if(result.error)throw new HttpError(409,'Please retry your existing order');order=result.data;}if(order.provider!=='wire')throw new HttpError(409,'A bank payment is pending');if(Date.now()-Date.parse(order.created_at)>47*3600000)throw new HttpError(409,'Contact support to reconcile this order');if(order.checkout_url)return Response.json({orderId:order.id,url:order.checkout_url});const session=await createCheckout(order,data.lang==='en'?'en':'mn');const saved=await db.from('membership_orders').update({wire_intent:session.intent,checkout_url:session.url}).eq('id',order.id).eq('status','pending');if(saved.error)throw new HttpError(503,'Unable to save checkout');return Response.json({orderId:order.id,url:session.url});}catch(e){return errorResponse(e);}}
